### ISSUE TITLE
Error using getting the Receipt

### ISSUE THREAD

**Issue by Manuelapr** [tidev/ti.storekit#37]
I'm using this module, but after loging in to my account I get this errror

`[ERROR] Failed to refresh receipt: Error Domain=SKErrorDomain Code=0 "Ocorreu um erro desconhecido" UserInfo={NSLocalizedDescription=Ocorreu um erro desconhecido, NSUnderlyingError=0x287c17030 {Error Domain=ASDErrorDomain Code=500 "Unhandled exception" UserInfo={NSUnderlyingError=0x287c16100 {Error Domain=AMSErrorDomain Code=100 "Authentication Failed" UserInfo={NSMultipleUnderlyingErrorsKey=(
[ERROR]     "Error Domain=AMSErrorDomain Code=2 \"Ocorreu um erro desconhecido. Volte a tentar.\" UserInfo={NSLocalizedDescription=Ocorreu um erro desconhecido. Volte a tentar.}",
[ERROR]     "Error Domain=AMSServerErrorDomain Code=-5000 \"(null)\" UserInfo={failureType=-5000, m-allowed=false, pings=(\n), cancel-purchase-batch=true, customerMessage=The Apple\U00a0ID you entered couldn\U2019t be found or your password was incorrect. Please try again.}"
[ERROR] ), NSLocalizedDescription=Authentication Failed, NSLocalizedFailureReason=The authentication failed.}}, NSLocalizedFailureReason=An unknown error occurred, NSLocalizedDescription=Unhandled exception}}}
[INFO]  Validating receipt.
[ERROR] Error: Receipt does not exist. Try refreshing the receipt.
[ERROR]     at  ([native code])
[ERROR]     at validate ()
[ERROR]     at  ()
[ERROR]     CoreFoundation 0x000000018a7c529c 5198FB57-5645-3B34-A49F-F32B52256CF3 + 627356
[ERROR]     libobjc.A.dylib 0x00000001a34bf744 objc_exception_throw + 60
[ERROR]     TitaniumKit 0x00000001011857c4 JavascriptNameForClass + 0
[ERROR]     Aqua-Info 0x0000000100287d84 -[TiStorekitModule receiptURL] + 228
[ERROR]     Aqua-Info 0x0000000100284fe0 -[TiStorekitModule validateReceipt:] + 332
[ERROR]     CoreFoundation 0x000000018a74db24 5198FB57-5645-3B34-A49F-F32B52256CF3 + 138020
[ERROR]     CoreFoundation 0x000000018a76b610 5198FB57-5645-3B34-A49F-F32B52256CF3 + 259600
[ERROR]     TitaniumKit 0x00000001011d1abc -[KrollMethod call:] + 1024
[ERROR]     TitaniumKit 0x00000001011d0df0 __KrollCallAsFunction_block_invoke + 36
[ERROR]     TitaniumKit 0x00000001011d0c08 KrollCallAsFunction + 396
[ERROR]     JavaScriptCore 0x0000000195e03028 62EB08D2-3EC0-33A3-9789-1FC94458F203 + 4718632
[ERROR]     JavaScriptCore 0x00000001966444ec 62EB08D2-3EC0-33A3-9789-1FC94458F203 + 13374700
[ERROR]     JavaScriptCore 0x0000000196677ac4 62EB08D2-3EC0-33A3-9789-1FC94458F203 + 13585092
[ERROR]     JavaScriptCore 0x0000000195d86d3c 62EB08D2-3EC0-33A3-9789-1FC94458F203 + 4209980
[ERROR]     JavaScriptCore 0x0000000195d834f8 62EB08D2-3EC0-33A3-9789-1FC94458F203 + 4195576
[ERROR]     JavaScriptCore 0x0000000195d834f8 62EB08D2-3EC0-33A3-9789-1FC94458F203 + 4195576
[ERROR]     JavaScriptCore 0x0000000195d59430 62EB08D2-3EC0-33A3-9789-1FC94458F203 + 4023344
[ERROR]     JavaScriptCore 0x0000000196556e1c 62EB08D2-3EC0-33A3-9789-1FC94458F203 + 12402204
[ERROR]     JavaScriptCore 0x00000001967de38c _ZN3JSC12profiledCallEPNS_14JSGlobalObjectENS_15ProfilingReasonENS_7JSValueERKNS_8CallDataES3_RKNS_7ArgListE + 96
[ERROR]     JavaScriptCore 0x0000000195e16568 JSObjectCallAsFunction + 520`

**Comment by hansemannn** [comment]
See https://stackoverflow.com/a/65551483/5537752
